// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc199.Robot2017.subsystems;

import org.usfirst.frc199.Robot2017.DashboardInterface;
import org.usfirst.frc199.Robot2017.PID;
import org.usfirst.frc199.Robot2017.Robot;
import org.usfirst.frc199.Robot2017.RobotMap;
import org.usfirst.frc199.Robot2017.commands.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class Shooter extends Subsystem implements DashboardInterface {
	double shootingAngle = Robot.getPref("shootingAngle", 0);
	double height = Robot.getPref("relativeHeightOfBoiler", 0);

	private final SpeedController shootMotor = RobotMap.shooterShootMotor;
	private final SpeedController feedMotor = RobotMap.shooterFeedMotor;
	private final Encoder shootEncoder = RobotMap.shooterShootEncoder;
	private final SpeedController turnMotor = RobotMap.turretTurnMotor;
	private final Encoder turretEncoder = RobotMap.turretTurretEncoder;
	private final SpeedController hoodMotor = RobotMap.hoodAngleMotor;
	private final Encoder hoodEncoder = RobotMap.hoodAngleEncoder;

	private PID ShooterPID = new PID("ShooterPID");

	private double prevEncoder = 0;
	private boolean shooterMotorStalled = false;

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	/**
	 * This method checks if 1)shootMotor is set to a high value 2)encoder is
	 * saying the shooter isn't moving 3)getPref is saying the shooterEncoder
	 * works
	 * 
	 * @return return whether shooter motor is deemed stalled, however, if it is
	 *         it automatically sets it to 0
	 */
	public boolean shooterMotorStalled() {

		if (Math.abs(shootMotor.get()) >= 0.2 && (shootEncoder.get() - prevEncoder) <= Robot.getPref("encoderOffset", 5)
				&& Robot.getPref("shooterEncoderWorks", 0) == 1) {
			shootMotor.set(0);
			System.out.println("Shooter Motor stalled, stopping motor.");
			prevEncoder = shootEncoder.get();
			shooterMotorStalled = true;
		} else {
			prevEncoder = shootEncoder.get();
			shooterMotorStalled = false;
		}
		return shooterMotorStalled;
	}

	/**
	 * Sets the shooter motor's speed (from -1.0 to 1.0).
	 * 
	 * @param rate
	 *            - speed to give the shooter motor
	 */
	public void runShootMotor(double rate) {
		shootMotor.set(rate);
	}

	/**
	 * Sets the feeder motor's speed (from -1.0 to 1.0).
	 * 
	 * @param rate
	 *            - speed to give the feeder motor
	 */
	public void runFeederMotor(double rate) {
		feedMotor.set(rate);
	}
	
	/**
	 * Sets the turret motor's speed (from -1.0 to 1.0).
	 * 
	 * @param rate
	 *            - speed to give the turret motor
	 */
	public void turret(double rate) {
		turnMotor.set(rate);
	}
	
	/**
	 * Sets the hood motor's speed (from -1.0 to 1.0).
	 * 
	 * @param rate
	 *            - speed to give the hood motor
	 */
	public void adjustHood(double rate) {
		hoodMotor.set(rate);
	}
	
	/**
	 * Tells the shooter motor's PID the target speed to reach.
	 * 
	 * @param targetRate
	 *            - target speed for shooter motor PID
	 */
	public void setPIDTarget(double targetRate) {
		ShooterPID.setTarget(targetRate);
	}

	/**
	 * Updates the shooter motor PID with the current speed from the encoder.
	 * 
	 * @param updateValuecurrent
	 *            shooter motor encoder speed
	 */
	public void updatePID(double updateValue) {
		ShooterPID.update(updateValue);
	}

	/**
	 * Gets the speed for the shooter motor from the shooter PID.
	 * 
	 * @return speed for motor
	 */
	public double getPIDOutput() {
		return ShooterPID.getOutput();
	}

	/**
	 * Passes the distance of the robot from the boiler through an equation to
	 * compute the speed at which we should be shooting.
	 * 
	 * @param distance
	 *            - in inches of the front of the robot from the boiler
	 * @return the ideal exit speed of the ball in inches/second
	 */
	public double convertDistanceToTargetSpeed(double distance) {
		return distance / Math.cos(shootingAngle)
				* Math.sqrt(386.09 / (2 * (distance * Math.tan(shootingAngle) - height)));
	}

	@Override
	public void displayData() {
		// TODO Auto-generated method stub
		SmartDashboard.putBoolean("shooterMotorStalled", shooterMotorStalled);
	}
}
