// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc199.Robot2017.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc199.Robot2017.Robot;
import org.usfirst.frc199.Robot2017.subsystems.DrivetrainInterface;

/**
 *
 */
public class AutoDrive extends Command {

	double targetDist, targetAngle;
<<<<<<< Updated upstream
	DrivetrainInterface drivetrain;
	
	public AutoDrive(double targetDist, double targetAngle, DrivetrainInterface drivetrain) {
=======

	public AutoDrive(double targetDist, double targetAngle) {

>>>>>>> Stashed changes
		requires(Robot.drivetrain);
		this.targetDist = targetDist;
		this.targetAngle = targetAngle;
		this.drivetrain = drivetrain;
	}

	// Called just before this Command runs the first time
	public void initialize() {
		drivetrain.resetEncoder();
		drivetrain.resetGyro();
		drivetrain.getDrivePID().setTarget(targetDist);
		drivetrain.getTurnPID().setTarget(targetAngle);

	}

	// Called repeatedly when this Command is scheduled to run
<<<<<<< Updated upstream
	public void execute() {
		drivetrain.autoDrive();
		if(drivetrain.currentControl()){
			drivetrain.shiftGears();
=======
	protected void execute() {
		Robot.drivetrain.autoDrive();
		if(Robot.drivetrain.currentControl()){
			Robot.drivetrain.shiftGears();
>>>>>>> Stashed changes
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	public boolean isFinished() {
		return drivetrain.getDrivePID().reachedTarget() || drivetrain.getTurnPID().reachedTarget();
		
	}

	// Called once after isFinished returns true
	public void end() {
		drivetrain.stopDrive();
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}
}
